<?php

/**
 * @file
 * Installation file for Analytics.js.
 */

/**
 * Implements hook_install().
 */
function analyticsjs_install() {
  // Universal web tracking opt-out & Compliance with Do Not Track.
  variable_set('analyticsjs_privacy', 1);
}

/**
 * Implements hook_uninstall().
 */
function analyticsjs_uninstall() {
  variable_del('analyticsjs_write_key');
  variable_del('analyticsjs_pages');
  variable_del('analyticsjs_visibility_pages');
  variable_del('analyticsjs_privacy');
}
