<?php

/**
 * @file
 * Drupal Module: Analytics.js
 *
 * Analytics.js is the easiest way to integrate analytics into your Drupal site.
 * By installing Analytics.js's Drupal plugin you can add any analytics service 
 * to your site without touching any code.
 */

/**
 * Define default path exclusion list to remove tracking from admin pages,
 * see http://drupal.org/node/34970 for more information.
 */
define('ANALYTICSJS_EXCLUSION_LIST', "admin\nadmin/*\nbatch\nnode/add*\nnode/*/*\nuser/*/*");

/**
 * Define default JS.
 */
define('ANALYTICSJS_CDN_JS', 'window.analytics||(window.analytics=[]),window.analytics.methods=["identify","track","trackLink","trackForm","trackClick","trackSubmit","page","pageview","ab","alias","ready","group","on","once","off"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;window.analytics.methods.length>i;i++){var method=window.analytics.methods[i];window.analytics[method]=window.analytics.factory(method)}window.analytics.load=function(t){var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)},window.analytics.SNIPPET_VERSION="2.0.8",window.analytics.load("ANALYTICSJS_WRITE_KEY");window.analytics.page();');

/**
 * Implements hook_permission().
 */
function analyticsjs_permission() {
  return array(
    'administer analyticsjs' => array(
      'title' => t('Administer analyticsjs'),
      'description' => t('Perform maintenance tasks for analyticsjs.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function analyticsjs_menu() {
  $items['admin/config/system/analyticsjs'] = array(
    'title' => 'Analytics.js Configuration',
    'description' => 'Configure <a href="https://segment.io/libraries/analytics.js" target="_blank"><b>Analytics.js</b></a> tracking behavior for your website.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('analyticsjs_admin_settings_form'),
    'access arguments' => array('administer analyticsjs'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'inc/analyticsjs.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_page_alter().
 */
function analyticsjs_page_alter(&$page) {
  $tracking = TRUE;

  // Disable tracking for visitors who have opted out via DNT header.
  if (variable_get('analyticsjs_privacy', 1) && !empty($_SERVER['HTTP_DNT'])) {
    $tracking = FALSE;
  }
  if ($tracking) {
    $write_key = variable_get('analyticsjs_write_key', '');
    if (empty($write_key)) {
      // Severity is emergency since the analyticsjs system would be usable.
      watchdog('analyticsjs', 'No Write Key has been Configured for Analytics.JS', NULL, WATCHDOG_EMERGENCY);
    }
    else {
      $script = str_replace('ANALYTICSJS_WRITE_KEY', $write_key, ANALYTICSJS_CDN_JS);

      // By default the script gets inserted in header.
      drupal_add_js($script, array('scope' => 'header', 'type' => 'inline'));
    }
  }
}
