<?php

/**
 * @file
 * Drupal Module: segmentio.
 *
 * Segmentio is the easiest way to integrate analytics into your Drupal site.
 * By installing segmentio's Drupal plugin you can add any analytics service
 * to your site without touching any code.
 */

/**
 * Implements hook_page_attachments().
 */
function segmentio_page_attachments(&$build) {
  $tracking = TRUE;

  // Disable tracking for visitors who have opted out via DNT header.
  if (\Drupal::config('segmentio.settings')->get('segmentio_privacy') && !empty($_SERVER['HTTP_DNT'])) {
    $tracking = FALSE;
  }
  if ($tracking) {
    $write_key = \Drupal::config('segmentio.settings')->get('segmentio_write_key');
    if (empty($write_key)) {
      // Severity is emergency since the segmentio system would be unusable.
      \Drupal::logger('segmentio')->emergency('No Write Key has been Configured for segmentio', []);
    }
    else {
      $variables = [];

      // Retrieve any set tracking events.
      $variables['track'] = segmentio_get_track_events(TRUE);

      // Retrieve any additional settings.
      $track = \Drupal::config('segmentio.settings')->get('segmentio_track');
      foreach ($track as $function => $enabled) {
        if ($enabled) {
          list($module, $hook) = explode(':', $function);
          $function = $module . '_' . $hook;
          $function($variables);
        }
      }
      $build['#attached']['library'][] = 'segmentio/segmentio';
      $build['#attached']['drupalSettings']['segmentio']['segmentio']['write_key'] = $write_key;
      $build['#attached']['drupalSettings']['segmentio']['segmentio']['variables'] = $variables;
    }
  }
}

/**
 * Implements hook_segmentio_info().
 */
function segmentio_segmentio_info() {
  return [
    'segmentio:segmentio_user' => t('User'),
    'segmentio:segmentio_node' => t('Node'),
  ];
}

/**
 * Segment.io callback; Retrieve Segment code for the logged in user.
 */
function segmentio_segmentio_user(&$variables = []) {
  $user = \Drupal::currentUser();
  if ($user) {
    $variables['identify']['userId'] = $user->id();
    $variables['identify']['traits']['name'] = $user->getAccountName();
    $variables['identify']['traits']['email'] = $user->getEmail();
  }
}

/**
 * Retrieve information from certain node views.
 */
function segmentio_segmentio_node(&$variables = []) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node) {
    $variables['page']['category'] = $node->getType();
    $variables['page']['name'] = $node->getTitle();
    $variables['page']['properties']['nid'] = $node->id();
    $variables['page']['properties']['uid'] = $node->getOwner()->id();
    if (isset($node->name)) {
      $variables['page']['properties']['name'] = $node->name;
    }
  }
}

/**
 * Set a tracking event.
 */
function segmentio_set_track_event($event = NULL, $properties = [], $options = [], $callback = NULL) {
  if (isset($event)) {
    if (!isset($_SESSION['segmentio'])) {
      $_SESSION['segmentio'] = [];
    }
    $track_event = [
      'event' => $event,
    ];
    if (!empty($properties)) {
      $track_event['properties'] = $properties;
    }
    if (!empty($options)) {
      $track_event['options'] = $options;
    }
    if (isset($callback)) {
      $track_event['callback'] = $callback;
    }
    $_SESSION['segmentio'][] = $track_event;

    // Mark this page as being uncacheable.
    \Drupal::service('page_cache_kill_switch')->trigger();
  }
  return isset($_SESSION['segmentio']) ? $_SESSION['segmentio'] : NULL;
}

/**
 * Retrieve a tracking event.
 */
function segmentio_get_track_events($clear_queue = TRUE) {
  if ($events = segmentio_set_track_event()) {
    if ($clear_queue) {
      unset($_SESSION['segmentio']);
    }
    if (isset($events)) {
      return $events;
    }
  }
  return [];
}
