<?php

/**
 * @file
 * Drupal Module: segmentio
 *
 * segmentio is the easiest way to integrate analytics into your Drupal site.
 * By installing segmentio's Drupal plugin you can add any analytics service
 * to your site without touching any code.
 */

/**
 * Define default JS.
 */
define('SEGMENTIO_CDN_JS', 'window.analytics||(window.analytics=[]),window.analytics.methods=["identify","track","trackLink","trackForm","trackClick","trackSubmit","page","pageview","ab","alias","ready","group","on","once","off"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;window.analytics.methods.length>i;i++){var method=window.analytics.methods[i];window.analytics[method]=window.analytics.factory(method)}window.analytics.load=function(t){var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"d2dq2ahtl5zl1z.cloudfront.net/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)},window.analytics.SNIPPET_VERSION="2.0.8",window.analytics.load("SEGMENTIO_WRITE_KEY");window.analytics.page();');

/**
 * Implements hook_permission().
 */
function segmentio_permission() {
  return array(
    'administer segmentio' => array(
      'title' => t('Administer segmentio'),
      'description' => t('Perform maintenance tasks for segmentio.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function segmentio_menu() {
  $items['admin/config/system/segmentio'] = array(
    'title' => 'Segmentio Configuration',
    'description' => 'Configure <a href="https://segment.io/libraries/analytics.js" target="_blank"><b>Segmentio</b></a> tracking behavior for your website.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('segmentio_admin_settings_form'),
    'access arguments' => array('administer segmentio'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'inc/segmentio.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_page_alter().
 */
function segmentio_page_alter(&$page) {
  $tracking = TRUE;

  // Disable tracking for visitors who have opted out via DNT header.
  if (variable_get('segmentio_privacy', 1) && !empty($_SERVER['HTTP_DNT'])) {
    $tracking = FALSE;
  }
  if ($tracking) {
    $write_key = variable_get('segmentio_write_key', '');
    if (empty($write_key)) {
      // Severity is emergency since the segmentio system would be unusable.
      watchdog('segmentio', 'No Write Key has been Configured for segmentio', NULL, WATCHDOG_EMERGENCY);
    }
    else {
      $script = str_replace('SEGMENTIO_WRITE_KEY', $write_key, SEGMENTIO_CDN_JS);

      // By default the script gets inserted in header.
      drupal_add_js($script, array('scope' => 'header', 'type' => 'inline'));
    }
  }
}
