segmentio.settings:
  type: mapping
  label: Settings
  mapping:
    segmentio_write_key:
      type: string
    segmentio_privacy:
      type: integer
    segmentio_track:
      type: sequence
      label: 'Additional information that should be tracked.'
      sequence:
        type: string
        label: 'Module'
